/**
 * Shared exam vocabulary — one definition of a slot, a booking and a result,
 * used by the student booking page, the examiner dashboard and the admin
 * screens so the three never drift apart.
 *
 * A slot is always presented the way the spec lists it: exam name, date,
 * slot window (length as allotted by admin), examiner name and the examiner's
 * WhatsApp number. Examiner details are resolved server-side from the
 * assignment — nothing here is ever typed by a learner.
 */
import { GraduationCap, Mic, MessageCircle, Phone, ScrollText, UserRound, type LucideIcon } from 'lucide-react';

export type ExamKind = 'CEFR' | 'Speaking';

export interface ExaminerContactFields {
  examiner_id?: string | null;
  examiner_name?: string | null;
  examiner_whatsapp?: string | null;
  examiner_phone?: string | null;
}

export interface ExamSlot extends ExaminerContactFields {
  id: string;
  kind: string;
  title: string;
  scheduled_at?: string | null;
  ends_at?: string | null;
  duration_minutes: number;
  capacity: number;
  seats_taken: number;
  seats_left: number;
  /** Set when this date was generated by a weekly slot rather than added by hand. */
  rule_id?: string | null;
}

/**
 * A **weekly** exam slot as admin sets it — "Sunday – 11:00 AM" — repeating
 * every week on that day and time until it is changed or removed. The dates
 * students actually book are generated from it (`upcoming_slots`).
 */
export interface ExamSlotRule extends ExaminerContactFields {
  id: string;
  kind: string;
  title: string;
  day_of_week: string;  // lowercase weekday name
  time_of_day: string;  // "HH:MM", IST
  duration_minutes: number;
  capacity: number;
  label: string;        // "Sunday – 11:00 AM", built server-side
  upcoming_slots: number;
  next_slot?: string | null;
}

export interface ExamResult {
  type: 'cefr_report' | 'certificate';
  level?: string | null;
  grade?: string | null;
  title?: string | null;
  remarks?: string | null;
  scores?: Record<string, unknown> | null;
  url?: string | null;
  verification_code?: string | null;
}

export interface ExamBooking extends ExaminerContactFields {
  id: string;
  exam_id: string;
  student_id: string;
  status: string;
  created_at: string;
  exam_title?: string | null;
  kind?: string | null;
  scheduled_at?: string | null;
  duration_minutes?: number | null;
  result?: ExamResult | null;
}

/** A booking as the examiner sees it, with the student resolved. */
export interface AssignedBooking extends ExamBooking {
  student_name?: string | null;
  student_photo_url?: string | null;
  student_gender?: string | null;
  student_cefr_level?: string | null;
  student_audience?: string | null;
  reported: boolean;
}

export interface ExaminerRow {
  id: string;
  username: string;
  full_name?: string | null;
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  is_active: boolean;
  created_at: string;
  last_login_at?: string | null;
  assigned_slots: number;
  upcoming_slots: number;
  students_booked: number;
  reports_submitted: number;
}

export interface Eligibility {
  [kind: string]: { allowed: number; used: number; remaining: number };
}

export const EXAM_KINDS: ExamKind[] = ['CEFR', 'Speaking'];
export const CEFR_LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
/** The four sub-skills an examiner scores on a CEFR report card. */
export const CEFR_SKILLS = ['listening', 'reading', 'speaking', 'writing'] as const;
/** Speaking test outcomes offered as quick picks (free text still allowed). */
export const SPEAKING_GRADES = ['Distinction', 'Merit', 'Pass', 'Needs Improvement'];
export const DEFAULT_SLOT_MINUTES = 20;
/** Weekday names as the API stores them; index 0 is Monday, as in Python. */
export const WEEKDAYS = [
  'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
] as const;

/** "Sunday – 11:00 AM" — the same label the API builds, for live previews. */
export function weeklySlotLabel(day: string, time: string) {
  const [h, m] = time.split(':').map(Number);
  if (Number.isNaN(h) || Number.isNaN(m)) return '';
  const suffix = h < 12 ? 'AM' : 'PM';
  return `${day.charAt(0).toUpperCase()}${day.slice(1)} \u2013 ${h % 12 || 12}:${String(m).padStart(2, '0')} ${suffix}`;
}

export const KIND_META: Record<string, { icon: LucideIcon; label: string; hint: string; accent: string }> = {
  CEFR: {
    icon: GraduationCap,
    label: 'CEFR tests',
    hint: 'Assess your English level (A1–C2)',
    accent: 'bg-emerald-500',
  },
  Speaking: {
    icon: Mic,
    label: 'Speaking tests',
    hint: 'Earn a SpeakEdge certificate',
    accent: 'bg-brand-gold',
  },
};

export function kindMeta(kind?: string | null) {
  return (kind && KIND_META[kind]) || {
    icon: ScrollText,
    label: `${kind ?? 'Exam'} tests`,
    hint: 'Included in your plan',
    accent: 'bg-brand/70',
  };
}

/** "Sat, 12 Sep 2026" */
export function fmtSlotDate(iso?: string | null) {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' });
}

/** "10:00 AM" */
export function fmtSlotTime(iso?: string | null) {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' });
}

/** "Sat, 12 Sep 2026 · 10:00 AM" — the slot as the learner sees it. */
export function fmtSlot(iso?: string | null) {
  const date = fmtSlotDate(iso);
  return date ? `${date} · ${fmtSlotTime(iso)}` : null;
}

/**
 * "10:00 AM – 10:20 AM (20 min)" — the booked window, derived from the slot
 * length the admin allotted rather than assumed.
 */
export function slotWindow(iso?: string | null, minutes?: number | null) {
  const mins = minutes ?? DEFAULT_SLOT_MINUTES;
  const start = fmtSlotTime(iso);
  if (!start) return `${mins} min slot`;
  const end = fmtSlotTime(new Date(new Date(iso as string).getTime() + mins * 60_000).toISOString());
  return `${start} – ${end} (${mins} min)`;
}

/** Digits-only wa.me link; Indian numbers get the country code when missing. */
export function whatsappHref(number?: string | null) {
  if (!number) return null;
  const digits = number.replace(/\D/g, '');
  if (!digits) return null;
  return `https://wa.me/${digits.length === 10 ? `91${digits}` : digits}`;
}

/**
 * Examiner name + WhatsApp exactly as assigned by the admin. Renders a
 * placeholder rather than nothing while a slot is still awaiting assignment,
 * so the learner is never left wondering.
 */
export function ExaminerContact({
  examiner,
  compact,
}: {
  examiner: ExaminerContactFields;
  compact?: boolean;
}) {
  const wa = whatsappHref(examiner.examiner_whatsapp);
  if (!examiner.examiner_name) {
    return (
      <span className="inline-flex items-center gap-1.5 text-sm text-slate-400">
        <UserRound size={14} className="shrink-0" />
        Examiner to be assigned
      </span>
    );
  }
  return (
    <div className={compact ? 'flex flex-wrap items-center gap-x-3 gap-y-1' : 'space-y-1'}>
      <span className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-700">
        <UserRound size={14} className="shrink-0 text-brand" />
        {examiner.examiner_name}
      </span>
      {wa ? (
        <a
          href={wa}
          target="_blank"
          rel="noreferrer"
          className="inline-flex items-center gap-1.5 text-sm font-medium text-emerald-600 hover:text-emerald-700"
        >
          <MessageCircle size={14} className="shrink-0" />
          {examiner.examiner_whatsapp}
        </a>
      ) : examiner.examiner_phone ? (
        <a
          href={`tel:${examiner.examiner_phone}`}
          className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-brand"
        >
          <Phone size={14} className="shrink-0" />
          {examiner.examiner_phone}
        </a>
      ) : (
        <span className="text-xs text-slate-400">WhatsApp number not published yet</span>
      )}
    </div>
  );
}
